### ISSUE TITLE
Module not found: Error: Can't resolve 'filestack-vue'

### ISSUE THREAD

**Issue by nezaboravi** [tipeio/filestack-vue#1]
Hey, thanks for the filestack-vue
I am trying to see it out, but cant import it.
What i have done is to follow step by step on read.me
Then, i run npm install, and i can see in filestack-vue in node_modules directory. It  is there
However, when i run webpack (npm run dev)
Module not found: Error: Can't resolve 'filestack-vue'
SO i did rm -rf npde_modules and reinstalled it again npm install but problem remains.
Any idea why?
Here is a snippet from my code:
`
import Filestack, { client } from 'filestack-vue';
`
ERROR in ./apps.js
Module not found: Error: Can't resolve 'filestack-vue' in '/webpack/src/admin'
 @ ./src/admin/apps.js 11:0-38

**Comment by pierrebraun** [comment]
Hey,
did you resolve it?

**Comment by RSeven** [comment]
I have the same issue :(

**Comment by gdi2290** [comment]
can you try again with version 2.0.0
