### ISSUE TITLE
Uncaught TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by kwfricke** [tipeio/filestack-vue#3]
I am getting the above error when trying to build this with Yarn. Any ideas? I have added everything correctly as far as I can tell :(

**Comment by gavinhoward100** [comment]
Getting the same issue.

**Comment by kwfricke** [comment]
@gavinhoward100 I was able to fix it by using an older version. When I switched back to these it works fine:

"filestack-js": "^0.11.5",
    "filestack-vue": "^2.0.0",

**Comment by gavinhoward100** [comment]
@kwfricke thank you!
